//// 
//// Autogenerated by xlw 
//// Do not edit this file, it will be overwritten 
//// by InterfaceGenerator 
////

#include "xlw/MyContainers.h"
#include <xlw/CellMatrix.h>
#include <stdexcept>
#include "cppinterface.h"
#include <xlw/xlwManaged.h>
using namespace System;
using namespace Runtime::InteropServices;





double mxlw_NormalOptionValue
		(
		double T,
		double F_0,
		double K,
		double sigma,
		bool isCall
		)
		{
		MANAGED_EXECL_BEGIN
			return NormalOptionValue(T,F_0,K,sigma,isCall );
		MANAGED_EXECL_END
		}

////////////////////////////////////

double mxlw_NormalOptionValueDeriv
		(
		double T,
		double F_0,
		double K,
		double sigma,
		bool isCall
		)
		{
		MANAGED_EXECL_BEGIN
			return NormalOptionValueDeriv(T,F_0,K,sigma,isCall );
		MANAGED_EXECL_END
		}

////////////////////////////////////

double mxlw_LognormalOptionValue
		(
		double T,
		double F_0,
		double K,
		double sigma,
		bool isCall
		)
		{
		MANAGED_EXECL_BEGIN
			return LognormalOptionValue(T,F_0,K,sigma,isCall );
		MANAGED_EXECL_END
		}

////////////////////////////////////

double mxlw_ConvertLognormalToNormalVol
		(
		double lognormalOptionPrice,
		double T,
		double F_0,
		double K,
		bool isCall
		)
		{
		MANAGED_EXECL_BEGIN
			return ConvertLognormalToNormalVol(lognormalOptionPrice,T,F_0,K,isCall );
		MANAGED_EXECL_END
		}

////////////////////////////////////

double mxlw_SABRImpliedNormalVol
		(
		double T,
		double F_0,
		double K,
		double sigma,
		double alpha,
		double beta,
		double rho
		)
		{
		MANAGED_EXECL_BEGIN
			return SABRImpliedNormalVol(T,F_0,K,sigma,alpha,beta,rho );
		MANAGED_EXECL_END
		}

////////////////////////////////////

double mxlw_SABRImpliedLogNormalVol
		(
		double T,
		double F_0,
		double K,
		double sigma,
		double alpha,
		double beta,
		double rho
		)
		{
		MANAGED_EXECL_BEGIN
			return SABRImpliedLogNormalVol(T,F_0,K,sigma,alpha,beta,rho );
		MANAGED_EXECL_END
		}

////////////////////////////////////

double mxlw_MonteCarloGetSABROptionPrice
		(
		double T,
		double F_0,
		double K,
		double sigma,
		double alpha,
		double beta,
		double rho,
		bool isCall,
		int numOfPath,
		int stepsInYear
		)
		{
		MANAGED_EXECL_BEGIN
			return MonteCarloGetSABROptionPrice(T,F_0,K,sigma,alpha,beta,rho,isCall,numOfPath,stepsInYear );
		MANAGED_EXECL_END
		}

////////////////////////////////////

